### ISSUE TITLE
No module "hid"

### ISSUE THREAD

**Issue by tobiz** [jaketeater/Very-Simple-USB-Relay#1]
I've installed everything as you describe on ubuntu 18.04 python 2.7 and it fails on (my line) line 3 "install hid" with:
~/Development$ python usbswitch-1.py
Traceback (most recent call last):
  File "usbswitch-1.py", line 3, in <module>
    import hid
ImportError: No module named hid

I tried changing this to "install hidapi as hid" and this gives:
~/Development$ python usbswitch-1.py
Traceback (most recent call last):
  File "usbswitch-1.py", line 114, in <module>
    relay = Relay(idVendor=0x16c0, idProduct=0x05df)
  File "usbswitch-1.py", line 22, in __init__
    self.h = hid.device()
NameError: global name 'hid' is not defined

So what's wrong?

**Comment by tobiz** [comment]
Ok, forget it, cracked it.  Tried re-install and it now works.
Code is just what I need.
Cheers
